spring.application.name=lettuce-test-app

# Metrics Configuration
metrics.dump.rate=PT5S

# Logging configuration
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n
logging.file.path=logs
logging.file.name=${logging.file.path}/lettuce-test-app.log
logging.logback.rollingpolicy.max-file-size=50MB

# Log levels
logging.level.io.lettuce.test=INFO
logging.level.io.lettuce.test.metrics=DEBUG
logging.level.org.springframework.data.redis=INFO
logging.level.io.lettuce.core=INFO
logging.level.io.lettuce.core.protocol.ConnectionWatchdog=DEBUG
logging.level.io.lettuce.core.protocol.ReconnectionHandler=DEBUG